#ifndef	__EEPROM_H__
#define	__EEPROM_H__

//***** EEPROM MEMORY MAP DEFINITIONS **********************

#define EE_TX0_CNT		    0x00		// OFFSET FOR TX0'S EEPROM SYNC COUNTER
#define EE_TX1_CNT		    0x08		// OFFSET FOR TX1'S EEPROM SYNC COUNTER
#define EE_TX2_CNT		    0x00		// OFFSET FOR TX2'S EEPROM SYNC COUNTER
#define EE_TX3_CNT		    0x08		// OFFSET FOR TX3'S EEPROM SYNC COUNTER

#define EE_VLOWL 	    0x07		// OFFSET FOR VLOW LATCH BYTE

#define EE_TX0_SER	    0x10		// OFFSET OF TX'S 64 BIT SEED VALUE			* FIRST TRANSMITTER *
#define EE_TX0_SEED	    0x14		// OFFSET OF TX'S 64 BIT SEED VALUE
#define EE_TX0_DISC	    0x1C		// OFFSET OF TX'S 16 BIT DISCRIMINATION VALUE
#define EE_TX0_KEY	    0x1E		// OFFSET OF TX'S 64 BIT ENCRYPTION KEY

#define EE_TX1_SER	    0x26		// OFFSET OF TX'S 64 BIT SEED VALUE 		* SECOND TRANSMITTER *
#define EE_TX1_SEED	    0x2A		// OFFSET OF TX'S 64 BIT SEED VALUE
#define EE_TX1_DISC	    0x32		// OFFSET OF TX'S 16 BIT DISCRIMINATION VALUE
#define EE_TX1_KEY	    0x34		// OFFSET OF TX'S 64 BIT ENCRYPTION KEY

#define EE_TX2_SER	    0x10		// OFFSET OF TX'S 64 BIT SEED VALUE			* THIRED TRANSMITTER *
#define EE_TX2_SEED	    0x14		// OFFSET OF TX'S 64 BIT SEED VALUE
#define EE_TX2_DISC	    0x1C		// OFFSET OF TX'S 16 BIT DISCRIMINATION VALUE
#define EE_TX2_KEY	    0x1E		// OFFSET OF TX'S 64 BIT ENCRYPTION KEY

#define EE_TX3_SER	    0x26		// OFFSET OF TX'S 64 BIT SEED VALUE 		* FOURTH TRANSMITTER *
#define EE_TX3_SEED	    0x2A		// OFFSET OF TX'S 64 BIT SEED VALUE
#define EE_TX3_DISC	    0x32		// OFFSET OF TX'S 16 BIT DISCRIMINATION VALUE
#define EE_TX3_KEY	    0x34		// OFFSET OF TX'S 64 BIT ENCRYPTION KEY

#define EE_TX0_CFG1	    0x3C		// OFFSET OF 16 BIT TRANSMITTER CONFIGURATION WORD
#define EE_SYS_CFG1	    0x3D		// OFFSET OF 16 BIT TRANSMITTER CONFIGURATION WORD
#define EE_TX1_CFG1	    0x3E		// OFFSET OF 16 BIT TRANSMITTER CONFIGURATION WORD
#define EE_SYS_CFG0	    0x3F

#define EE_TX2_CFG1	    0x3C		// OFFSET OF 16 BIT TRANSMITTER CONFIGURATION WORD
#define EE_TX3_CFG1	    0x3E		// OFFSET OF 16 BIT TRANSMITTER CONFIGURATION WORD

unsigned char ee_read(unsigned char eeprom_adress);
unsigned char ee_write(unsigned char eeprom_adress, unsigned char eeprom_data);

#endif